### ISSUE TITLE
Imagen de Formato 

### ISSUE THREAD

**Issue by VivianaMarcela** [selobu/GestionHSEQ#10]
![image](https://user-images.githubusercontent.com/80597326/111648681-9d2fc400-87d1-11eb-845b-a662cd438f8b.png)
Al subir la foto se evidencia "$clean" al final del recuadro.

**Comment by selobu** [comment]
Falta indicar la versión del sistema donde dice MILESTONE. Ya fué corregido en la ultima versión

**Comment by selobu** [comment]
Se verificó en la última versión que se corrigió
