### ISSUE TITLE
Lista Editable aún no disponible

### ISSUE THREAD

**Issue by VivianaMarcela** [selobu/GestionHSEQ#11]
![image](https://user-images.githubusercontent.com/80597326/111662532-ff8ec180-87dd-11eb-8718-21a44716b1a1.png)
Hola Sebas me encuentro probando y corrigiendo errores y me doy cuenta que la opciòn de "lista editable" aun no se encuentra disponible entre las opciones de respuesta.

**Comment by selobu** [comment]
Por favor indicar la versión de la aplicación.  En la última versión aparece el control
![Captura control](https://user-images.githubusercontent.com/11469144/111708939-c1f95b00-8814-11eb-8b96-0bc3f912549f.PNG)

**Comment by VivianaMarcela** [comment]
Ya aparece, version 16

**Comment by VivianaMarcela** [comment]
Ya aparece, version 16
