### ISSUE TITLE
Error en lista editable

### ISSUE THREAD

**Issue by VivianaMarcela** [selobu/GestionHSEQ#12]
![image](https://user-images.githubusercontent.com/80597326/111892217-64f1d680-89c7-11eb-8823-bf010a49fcd6.png)

En esta imagen pertenece a la lista de chequeo de la perforadora Hidráulica, se observa que se le indica que el tipo de respuesta es "selección editable", yo entiendo de selección editable que se puede escoger una de las opciones predeterminadas, y en caso de seleccionar "otro" me permite agregar otra respuesta. Y esto no sucede así; ya que al guardar y  entrar a responder el formato las opciones predeterminadas no aparecen, solo permite escribir.
![image](https://user-images.githubusercontent.com/80597326/111892421-64f2d600-89c9-11eb-91d3-373eb7f1726a.png)

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111892440-966ba180-89c9-11eb-85ce-a185228d3f77.png)
y en el momento en que se entra a editar de nuevo el formato, las opciones preterminadas ya no estan.

**Comment by selobu** [comment]
Se corrigió.

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111892630-1d6d4980-89cb-11eb-9582-56c2868647c8.png)
Lo mismo ocurre desde la pregunta número 6 en adelante en donde la lista predeterminada sería "Bueno" "Regular" "Malo" "Observaciones", la idea es poder escoger una respuesta y en caso de tener una observación poder escribirla.
