### ISSUE TITLE
Numeración de las preguntas

### ISSUE THREAD

**Issue by selobu** [selobu/GestionHSEQ#2]
Cuando se utiliza la edición de las preguntas y se quiere adicionar una nueva el sistema automáticamente selecciona preguntas existentes al mismo tiempo y generar errores de edición

**Comment by selobu** [comment]
Se corrige el fallo

**Comment by VivianaMarcela** [comment]
![imagen_2021-03-15_215055](https://user-images.githubusercontent.com/80597326/111248750-84a88980-85d8-11eb-81ee-162e095ecaee.png)

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111054822-bcc79500-843d-11eb-9d87-c8c5b190492d.png)
![image](https://user-images.githubusercontent.com/80597326/111377131-4e1d4e00-866e-11eb-8c80-2a37b8d41abc.png) 
![image](https://user-images.githubusercontent.com/80597326/111377454-ae13f480-866e-11eb-87c9-dc354ca5d0c4.png)

Ya se agrego la foto al carnet con cod QR, en línea ya actualizo los cambios, y en la aplicación aun no se actualizas. adjunto imágenes para su verificación.

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111377605-d865b200-866e-11eb-9a18-d9e9377a8476.png)
Cada que se accede para hacer un formato nuevo y lo guardas sin importar que digites "versión1" y lo abras para verificar como quedo toca entrar a editar la versión ya que se cambia se digito el 1, se guarda y aparece el nùmero 7 y luego de guardar y darle de nuevo editar por 2da vez aparece 8..... y asì sucesivamente.

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111378140-76597c80-866f-11eb-9f16-d00d8cc1bacd.png)

En esta imagen se observa que esta pregunta se agrega una Descripción a la misma, se guarda y en el momento de ver el formato listo para diligenciarlo no aparece la descripción. 
![image](https://user-images.githubusercontent.com/80597326/111378202-840f0200-866f-11eb-9b54-b017b01bc609.png)
Y al entrar a editar de nuevo la descripción no aparece. toca digitarla de 0.

**Comment by VivianaMarcela** [comment]
![image](https://user-images.githubusercontent.com/80597326/111378507-e2d47b80-866f-11eb-8a5f-de0211de0be4.png)

Doy clic en la casita, formatos, seleccionó el formato con nombre ATS me salen el formato a diligenciar me voy a los 3 puntitos  le doy en editar
 Y se abre de inmediato como si fuera a empezar con un formato nuevos. No me sale el formato a editar. Repito el proceso para verificar los pasos y me sale lo mismo.

**Comment by VivianaMarcela** [comment]
Me encuentro sin internet y me dispongo a probar la aplicación Gestionhseq, para probar su funcionamiento off-line y se me abre una una ventana blanca dentro de la aplicación llamando a selobu…. No alcanzo a tomar pantallazo ya que en ese momento regresa el internet y me funciona. Prueba para verificar si ocurre lo mismo. Pero ya me carga sin problema. Creo que correspondió a que la versión era la .13 y ahora está en la 14.
