### ISSUE TITLE
No aparece la descripción de la pregunta

### ISSUE THREAD

**Issue by selobu** [selobu/GestionHSEQ#7]
![image](https://user-images.githubusercontent.com/11469144/111471027-73ee3580-86f6-11eb-9142-7d478f7d0038.png)

En esta imagen se observa que esta pregunta se agrega una Descripción a la misma, se guarda y en el momento de ver el formato listo para diligenciarlo no aparece la descripción.

![image](https://user-images.githubusercontent.com/11469144/111471056-79e41680-86f6-11eb-812a-9d21c6f90a95.png)

Y al entrar a editar de nuevo la descripción no aparece. toca digitarla de 0.

**Comment by selobu** [comment]
Se corrige la falla, la descripción aparece como un símbolo de admiración gris al costado derecho de  la pregunta como se presenta en la imagen

![image](https://user-images.githubusercontent.com/11469144/111476518-3a202d80-86fc-11eb-9863-7aad2b80716c.png)

**Comment by VivianaMarcela** [comment]
Ya se probó y en efecto aparece el comentario

**Comment by selobu** [comment]
Cerrado
