### ISSUE TITLE
Al tratar de editar un formato aparece uno en blanco

### ISSUE THREAD

**Issue by selobu** [selobu/GestionHSEQ#8]
![image](https://user-images.githubusercontent.com/11469144/111471105-89635f80-86f6-11eb-9119-0900e28592d6.png)

Doy clic en la casita, formatos, seleccionó el formato con nombre ATS me salen el formato a diligenciar me voy a los 3 puntitos le doy en editar
Y se abre de inmediato como si fuera a empezar con un formato nuevos. No me sale el formato a editar. Repito el proceso para verificar los pasos y me sale lo mismo.

**Comment by selobu** [comment]
El error se genera debido a que demora en cargar las pregruntas, por eso te aparece en blanco

**Comment by selobu** [comment]
Se adiciona un indicador cuando está cargando un formulario.

**Comment by selobu** [comment]
**Pendiente cargar formatos parcialmente de a 10 preguntas!**

**Comment by VivianaMarcela** [comment]
Ya puedo ver el Indicador cargando,.

**Comment by selobu** [comment]
Pendiente acelerar la carga del formato para editar.
